---
title: "Simulación de producción eléctrica de una granja eólica"
author: "Anderson Acuña, Marlon Barajas, Fabián Hernández"
date: "2024-06-19"
output:
  html_document:
    theme: journal
    toc: yes
    toc_float:
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tratamiento y exploración de datos
```{r}
wind_data <- read.csv("./velocidad-viento-duitama-boyaca.csv")
```

Se selecciona la columna relevante para la simulación, que contiene los valores de la velocidad del viento en metros por segundo.
```{r}
wind_data <- subset(wind_data, select = c("ValorObservado"))
colnames(wind_data) <- c("wind_speed")
head(wind_data)
```

Frecuencias de la velocidad del viento.
```{r}
hist(wind_data$wind_speed,
     ylim = c(0, 350),
     col = "orange",
     main = "Histograma de las velocidades del viento",
     xlab = "Velocidad del viento [m/s]",
     ylab = "Frecuencia absoluta")
```

# Función de potencia
```{r}
p <- function(v) {
  if(v > 4 & v <= 14) return((25.12 - 39.05*v + 7.21*(v^2)) * 1.5)
  else if(v > 14 & v <= 20) return(1500)
  else return(0)
}
```


















